### ISSUE TITLE
Request for Specific changes

### ISSUE THREAD

**Issue by btmcmahan** [dustedrob/BluetoothLeGatt#1]
Hi dustedrob,
I've been working on a BluetoothLeGatt project for a while, and I was wanting to sort of "start over" with an updated sample project.

Can you offer any specifics on what types of changes & improvements you have made?  Thanks for your hard work!

**Comment by dustedrob** [comment]
It uses the latest Bluetooth LE APIs for scanning and also adds peripheral mode with BluetoothLEAdvertiser. Everything else is the same.
